### PR TITLE
add StatsService.GetSysStats

### PR DESCRIPTION
**Pull request by vcptr**
1. add `StatsService.GetSysStats` call to `v2ctl` to retrieve core running data, example:
```
$ /usr/bin/v2ray/v2ctl api --server=127.0.0.1:10085 StatsService.GetSysStats ''
NumGoroutine: 16
NumGC: 5
Alloc: 717048
TotalAlloc: 5185696
Sys: 71762168
Mallocs: 55768
Frees: 48457
LiveObjects: 7311
PauseTotalNs: 706772
Uptime: 589
```

2. fixed bug running command `v2ctl api` without arguments, hangs forever with no output/error.

### CODE REVIEW

**Comment by xiaokangwang** [comment]
This pull request have added a 3 second timeout to grpc request in v2ctl. I believe this behavior should be reflected in document to prevent confusion in the future.

**Comment by vcptr** [comment]
Actually the previous behavior is more confusing,  grpc dial have a infinite timeout, the command just hangs forever.

**Comment by xiaokangwang** [comment]
Yes, however, we can't assume all commands can be completed in 3 seconds.

**Comment by vcptr** [comment]
I think we can.

Any cli command does not response in a human bearable time and tells what happened, is bad design.

A three seconds waiting is suitable in this situation.

**Comment by xiaokangwang** [comment]
Currently, this is the case, but I think this change should be documented nonetheless.

**Comment by vcptr** [comment]
a notice line added, heres the help text:

```
$ ./v2ctl api --help
Usage of api:
  -server string
        Server address (default "127.0.0.1:8080")
v2ctl api [--server=127.0.0.1:8080] Service.Method Request
Call an API in an V2Ray process.
The following methods are currently supported:
        LoggerService.RestartLogger
        StatsService.GetStats
        StatsService.QueryStats
API calls in this command have a timeout to the server of 3 seconds.
Examples:
v2ctl api --server=127.0.0.1:8080 LoggerService.RestartLogger '' 
v2ctl api --server=127.0.0.1:8080 StatsService.QueryStats 'pattern: "" reset: false'
v2ctl api --server=127.0.0.1:8080 StatsService.GetStats 'name: "inbound>>>statin>>>traffic>>>downlink" reset: false'
v2ctl api --server=127.0.0.1:8080 StatsService.GetSysStats ''
```

**Comment by xiaokangwang** [comment]
I believe this pull request is ready to be merged.

**Pull request merged**
