### PR TITLE
Show IP address when installation is done.

### PR DESCRIPTION
**Pull request by Ariselia**

### CODE REVIEW

**Comment by DarienRaymond** [comment]
What are you trying to achieve? and why is this change related to the installation?

**Comment by Ariselia** [comment]
Will make config for clients easier.

**Comment by xiaokangwang** [comment]
I recommend to use $(ip addr)/$(ifconfig) instead of external website.

This should able to decrease data expose.

**Comment by xiaokangwang** [comment]
There are other things need to be considered: if the user is using a VPS within NAT, notably lowendspirit series and some vps in China, it can be really difficult for scripts to detect the IP correctly and check whether port is reachable, given no data exposed to 3rd-party.

**Comment by xiaokangwang** [comment]
Should any other tool or user relay on this script to deduce reachable address, this could be an issue that effect their effectiveness.

**Comment by DarienRaymond** [comment]
I don't think this is a necessary functionality for the installation script. User doesn't have to use the IP of the VPS for proxy connections. The IP displayed here may be misleading. If you need such functionality, you may wrap your own script and add any logic that suitable for your scenario.

**Pull request closed without merging**
