### PR TITLE
Add rate limit

### PR DESCRIPTION
**Pull request by hikaruchang**
Add rate limit feature, but I don't know how to get the value from level entry.

"levels": {
    "0": {
      ...
      "rate": 100
    }
}

### CODE REVIEW

**Comment by kslr** [comment]
such as https://github.com/v2ray/v2ray-core/blob/90a61a5b046c0218d9412f0a39d461dbb4dc50aa/infra/conf/router.go#L15

**Comment by hikaruchang** [comment]
> * Is this location suitable？
> * Use readable format, such as 1K 1M 1G etc

The default unit is KB/s,
I tried to read the configuration file, but failed.
Please add it under policy - level
For example:
`"levels": {
     "0": {
          ...
          "rate": 100
     }
}`

**Comment by kslr** [comment]
Please add formatting and transfer to https://github.com/v2fly/v2ray-core

**Comment by hikaruchang** [comment]
> Please add formatting and move to https://github.com/v2fly/v2ray-core

What is the difference between v2ray and v2fly?

**Comment by NetHeritage** [comment]
> 
> 
> > Please add formatting and move to https://github.com/v2fly/v2ray-core
> 
> What is the difference between v2ray and v2fly?

v2ray is dead. Long live v2fly.

**Comment by zhaoyadong00** [comment]
多用户 有内存泄露问题

**Comment by hikaruchang** [comment]
> 多用户 有内存泄露问题

临时做了一个，没有做安全考虑，之后有时间会写个优化的。

**Comment by zhaoyadong00** [comment]
rate.go
package dispatcher

import (
	"github.com/juju/ratelimit"
	"io"
	"v2ray.com/core/common"
	"v2ray.com/core/common/buf"
)

type Writer struct {
	writer  buf.Writer
	limiter *ratelimit.Bucket
	w       io.Writer
}

func RateWriter(writer buf.Writer, limiter *ratelimit.Bucket) buf.Writer {
	return &Writer{
		writer:  writer,
		limiter: limiter,
	}
}

func (w *Writer) Close() error {
	return common.Close(w.writer)
}

func (w *Writer) WriteMultiBuffer(mb buf.MultiBuffer) error {
	w.limiter.Wait(int64(len(mb)))
	return w.writer.WriteMultiBuffer(mb)
}

default.go

if p.Buffer.Rate != 0 {
			bucket := ratelimit.NewBucket(time.Duration((int64(time.Second)/int64(p.Buffer.Rate))*2), 1024)
			inboundLink.Writer = RateWriter(inboundLink.Writer, bucket)
			outboundLink.Writer = RateWriter(outboundLink.Writer, bucket)
		}

**Comment by zhaoyadong00** [comment]
我修改了一版 测试下来 没啥问题

**Comment by ifworldok** [comment]
@hikaruchang 感谢作者付出，能正常使用，发现限速后，每隔一分钟左右网速会突然窜高，几秒钟后恢复正常，一直循环此过程

**Comment by ifworldok** [comment]
@zhaoyadong00 试了下你的修改版，限速单位跟原作者的一样吗，我测试后大部分时间基本没速度，有时又突然窜高

**Comment by zhaoyadong00** [comment]
> @zhaoyadong00 试了下你的修改版，限速单位跟原作者的一样吗，我测试后大部分时间基本没速度，有时又突然窜高

func (l *RateLimiter) RateWait(count int64) {
	l.count += count
	t := time.Duration(l.count)*time.Second/l.rate - time.Since(l.t)
	if t > 0 {
		time.Sleep(t)
	}
}
作者的逻辑是 time.sleep

**Comment by zhaoyadong00** [comment]
> @zhaoyadong00 试了下你的修改版，限速单位跟原作者的一样吗，我测试后大部分时间基本没速度，有时又突然窜高

单位不一样 等等 会在发一个稳定版本

**Comment by zhaoyadong00** [comment]
rate.go 新增
type Bucket struct {
	User   *protocol.MemoryUser
	Bucket *ratelimit.Bucket
}
type BucketManage struct {
	Users map[string]*Bucket
	sync.RWMutex
}

func (b *BucketManage) GetUserBucket(u *protocol.MemoryUser, rate int64) *ratelimit.Bucket {
	if len(u.Email) > 0 && b.Users[u.Email] != nil {
		return b.Users[u.Email].Bucket
	} else {
		bucket := ratelimit.NewBucket(time.Duration(int64(time.Second)/rate*8), 1024)
		bu := &Bucket{
			User:   u,
			Bucket: bucket,
		}
		b.Lock()
		defer b.Unlock()
		b.Users[u.Email] = bu
		return bucket
	}
}
func NewBucketMange() *BucketManage {
	return newBucketMange
}

var newBucketMange *BucketManage

func init() {
	newBucketMange = new(BucketManage)
	newBucketMange.Users = make(map[string]*Bucket)
}


default.go 更新

bm := NewBucketMange()
			bucket := bm.GetUserBucket(user, int64(p.Buffer.Rate))
			inboundLink.Writer = RateWriter(inboundLink.Writer, bucket)
			outboundLink.Writer = RateWriter(outboundLink.Writer, bucket)

**Comment by ifworldok** [comment]
@zhaoyadong00 水桶算法可以正常工做了，另外请教下动态添加 routing rules 有办法实现吗, 比如下面三条 blocked 的tag 实时的添加到路由规则并生效
[tag:"blocked"  protocol:"bittorrent" tag:"blocked"  user_email:"1@emali.com" tag:"blocked"  source_geoip:{cidr:{ip:":\xf1\xd6\x23"  prefix:32}}]

**Comment by zhaoyadong00** [comment]
> @zhaoyadong00 水桶算法可以正常工做了，另外请教下动态添加 routing rules 有办法实现吗, 比如下面三条 blocked 的tag 实时的添加到路由规则并生效
> [tag:"blocked" protocol:"bittorrent" tag:"blocked" user_email:"[1@emali.com](mailto:1@emali.com)" tag:"blocked" source_geoip:{cidr:{ip:":\xf1\xd6\x23" prefix:32}}]

看了下 需要操作添加一下rpc接口 操作Router.rules 这个slice

**Comment by hikaruchang** [comment]
> rate.go 新增
> type Bucket struct {
> User *protocol.MemoryUser
> Bucket *ratelimit.Bucket
> }
> type BucketManage struct {
> Users map[string]*Bucket
> sync.RWMutex
> }
> 
> func (b *BucketManage) GetUserBucket(u *protocol.MemoryUser, rate int64) _ratelimit.Bucket { if len(u.Email) > 0 && b.Users[u.Email] != nil { return b.Users[u.Email].Bucket } else { bucket := ratelimit.NewBucket(time.Duration(int64(time.Second)/rate_8), 1024)
> bu := &Bucket{
> User: u,
> Bucket: bucket,
> }
> b.Lock()
> defer b.Unlock()
> b.Users[u.Email] = bu
> return bucket
> }
> }
> func NewBucketMange() *BucketManage {
> return newBucketMange
> }
> 
> var newBucketMange *BucketManage
> 
> func init() {
> newBucketMange = new(BucketManage)
> newBucketMange.Users = make(map[string]*Bucket)
> }
> 
> default.go 更新
> 
> bm := NewBucketMange()
> bucket := bm.GetUserBucket(user, int64(p.Buffer.Rate))
> inboundLink.Writer = RateWriter(inboundLink.Writer, bucket)
> outboundLink.Writer = RateWriter(outboundLink.Writer, bucket)

学习了，感谢指正

**Comment by NutterChen** [comment]
此pr的作者还在工作为此吗？

**Comment by kslr** [comment]
https://github.com/v2fly/v2ray-core/pull/402

**Pull request closed without merging**
