### PR TITLE
refactor: Clean up install-release.sh

### PR DESCRIPTION
**Pull request by xymopen**

### CODE REVIEW

**Comment by kslr** [comment]
@vcptr

**Comment by kslr** [comment]
Do you consider using smaller changes and multiple PR?

**Comment by xymopen** [comment]
Maybe I'll do it when i'm available.

**Comment by kslr** [comment]
Do you need to keep the PR?

**Comment by xymopen** [comment]
Main features have been merge but I would like to make some more polishes. Anyway this PR should be closed.

**Pull request closed without merging**
