### PR TITLE
修复一个导致 TPROXY 下 v2ray 断流的问题

### PR DESCRIPTION
**Pull request by FH0**
代码来自 #1530 ，这对我有用

### CODE REVIEW

**Comment by FH0** [comment]
这么久都没有回复吗，行还是不行。代码我是抄的，原理不懂，可以和原作者交流。 @kslr @lucifer9 @vcptr

**Comment by agioi** [comment]
https://github.com/v2ray/v2ray-core/pull/1530#issuecomment-458140858

**Comment by yichya** [comment]
tested this patch on my openwrt router running tproxy mode. 
solved my problem of being unable to use zoom or lark (feishu) video meeting.

**Comment by agioi** [comment]
We are not going to rely on something "tested work". It should be correct.

**Comment by kslr** [comment]
我将临时合并这个解决方案

**Comment by cod1ingcoding** [comment]
问题得到解决，而且感觉quic速度明显稍微有所提升。

**Comment by cod1ingcoding** [comment]
UDP断流有所缓解， 表现为原先断流就连不上， 这个提交达到断流卡死过一会还是能连上。

**Comment by agioi** [comment]
Apparently this patch is NOT "tested work". If fails several test cases in windows.

**Comment by agioi** [comment]
Apparently this patch is NOT "tested work". If fails several test cases on windows.

**Comment by FH0** [comment]
> Apparently this patch is NOT "tested work". If fails several test cases on windows.

As far as I know, tproxy only works on linux. Do you mean after applying this patch, v2ray will not work on windows as before?

**Comment by agioi** [comment]
> > Apparently this patch is NOT "tested work". If fails several test cases on windows.
> 
> As far as I know, tproxy only works on linux. Do you mean after applying this patch, v2ray will not work on windows as before?

Yes

**Comment by FH0** [comment]
> > > Apparently this patch is NOT "tested work". If fails several test cases on windows.
> > 
> > 
> > As far as I know, tproxy only works on linux. Do you mean after applying this patch, v2ray will not work on windows as before?
> 
> Yes

I'm sorry for that. But I am not a coder. It will be solved by others.

**Pull request merged**
