### PR TITLE
Enable TLS 1.3

### PR DESCRIPTION
**Pull request by ZenerBarrier**
This pull request including the following changes:
1. Set mandatory environment variables for enabling TLS 1.3 in go 1.12 ([https://golang.org/pkg/crypto/tls/](https://golang.org/pkg/crypto/tls/))
2. Add 3 TLS 1.3 ciphers.
3. Prefer `AES-128-GCM-SHA256` as Encryption(+AEAD MAC) than `CHACHA20-POLY1305`
4. Prefer `ECDSA` than `RSA` as Authentication in TLS 1.0 to TLS 1.2
5. Change `GOCACHE` to an absolute path `/tmp` to avoid failing the bazel building (#1643 #1650 )

P.S.
Q. Why this account is registered recently
A. It's not my main account, it's a mitigation of privacy compromising.

### CODE REVIEW

**Comment by xiaokangwang** [comment]
You should have submit 3 changes separately so that they can be discussed individually. 

You are setting tls13 environment variable from config.pb.go, which can be regenerated at any time.

It is better to set it in a separate file, in a way that can be disabled.

https://github.com/v2fly/v2ray-core/commit/fa976b8a1bd0cbe1599adcf0f4d25be9742a43a2

Can you provide justification for "Prefer AES-128-GCM-SHA256 as Encryption(+AEAD MAC) than CHACHA20-POLY1305" ?

As for “Change GOCACHE to an absolute path /tmp to avoid failing the bazel building”, there are other [PR](https://github.com/v2ray/v2ray-core/pull/1650) addressing this. I recommend you to drop this from your PR so that discussions can be focus on other topic.

**Comment by ZenerBarrier** [comment]
> 
> Can you provide justification for "Prefer AES-128-GCM-SHA256 as Encryption(+AEAD MAC) than CHACHA20-POLY1305" ?
> 

The reason to give `AES-128-GCM-SHA256` a higher priority than `CHACHA20-POLY1305` is most of devices has specified instruction sets to enhance the performance of AES-GCM encryption (e.g. AES-NI). 

If CHACHA20 ciphersuites is the first option of the client, some TLS server (e.g. those use OpenSSL with `SSL_OP_PRIORITIZE_CHACHA` option parameter) will recognize the client as 'NO AES instruction sets' and use CHACHA20 ciphersuites.

Thus, **Most of TLS Clients use AES-128-GCM-SHA256 -> CHACHA20-POLY1305 -> AES-256-GCM-SHA384 as the ciphersuites priority when running on a platform with AES instruction sets**, this change is an enhancement on performance and makes the TLS of V2Ray more similar to a common one like Google Chrome or Mozilla Firefox.

**Comment by ZenerBarrier** [comment]
Should I close this PR and re-create one, keeps the change on tls13 ciphers only?
(Remove the change to `build.bzl` and tls13 environment variable)

It's my first PR, sorry for any inconvenient caused by me.

**Comment by kslr** [comment]
Yes
https://github.com/v2fly/v2ray-core/commit/fa976b8a1bd0cbe1599adcf0f4d25be9742a43a2
https://github.com/v2fly/v2ray-core/commit/1a7b2337f81cbdbe7da06d5cf5c916de899ef372

**Pull request closed without merging**
