### PR TITLE
Support http outbound

### PR DESCRIPTION
**Pull request by flyxl**
Support http outbound by HTTP CONNECT method

### CODE REVIEW

**Comment by hanazaki05** [comment]
It is recommended to write comments in English, it keeps comments consistent and making it easier to maintain.

**Comment by flyxl** [comment]
> It is recommended to write comments in English, it keeps comments consistent and making it easier to maintain.

done

**Comment by kslr** [comment]
Thank you for your work
if you are interested, you can join https://t.me/joinchat/JiDjBFceHguFwQ_K4COQMw

**Comment by flyxl** [comment]
> https://t.me/joinchat/JiDjBFceHguFwQ_K4COQMw

This link seems to be expired

**Comment by kslr** [comment]
https://t.me/joinchat/JiDjBFceHgsmmj6qSQVl-g

**Pull request merged**
