### PR TITLE
Merge pull request #1 from v2ray/master

### PR DESCRIPTION
**Pull request by leaves615**
merge from v2ray

### CODE REVIEW

**Comment by v2ray** [comment]
What is this? I can't see any changes.

**Comment by xiaokangwang** [comment]
这个PR是误操作吧， 可能时以前fork了你的repo，后来用github的PR用能把比较新的你的代码pull到了他自己的代码库之后，把这个merge的commit的PR到你这里了。

**Comment by v2ray** [comment]
Closing as the author doesn't provide reasonable clarification for this PR.

**Comment by leaves615** [comment]
sorry 我只是想pull

**Pull request closed without merging**
